package es.urjc.etsii.grafo.PSSC.constructives;

import es.urjc.etsii.grafo.PSSC.model.PSSCInstance;
import es.urjc.etsii.grafo.PSSC.model.PSSCSolution;
import es.urjc.etsii.grafo.create.Constructive;
import es.urjc.etsii.grafo.util.random.RandomManager;

/**
 * Create a random solution for the PSSC: Partial Set Covering Problem
 */
public class PSSCRandomConstructive extends Constructive<PSSCSolution, PSSCInstance> {

    /**
     * Construct a random solution for the PSSC problem by adding random sets until solution is covered
     * Note that this random method will always generate a feasible solution, as the worst case is adding all sets,
     * which is guaranteed to be feasible.
     * @param solution Empty solution, for example generated by calling its constructor @ref{PSSCSolution#PSSCSolution(PSSCInstance)}
     * @return a feasible solution
     */
    @Override
    public PSSCSolution construct(PSSCSolution solution) {
        var rnd = RandomManager.getRandom();
        int nSets = solution.getInstance().getnSets();
        while (!solution.isCovered()) {
            int set = rnd.nextInt(nSets);
            solution.addSet(set);
        }
        solution.notifyUpdate();
        return solution;
    }
}
